
services:
  go-learn:
    container_name: go-learn
    entrypoint: tail -f /dev/null
    image: golang:1.20.3-bullseye
    volumes:
     - ./:/go/src/go-learn
     - go-pkg:/go/pkg
     - go-pkg:/go/bin

  postgres:
    image: postgres:16
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=employee

volumes:
 go-pkg: 